### ISSUE TITLE
native method removed from asio use native_handle

### ISSUE THREAD

**Issue by theSundayProgrammer** [kenba/via-httplib#3]
via/comms/connection.hpp:476:66: error: ‘asio::ip::tcp::socket’ has no member named ‘native’

use native_handle. The method 'native' was deprecated earlier and removed in later versions of asio.

**Comment by kenba** [comment]
Thanks you for bringing it to my attention, I've put the fix in the develop branch for now.
BTW which compiler did you use and which version of boost?
GCC didn't even emit a warning on 1.57, let alone an error...

**Comment by theSundayProgrammer** [comment]
I used the asio from https://github.com/chriskohlhoff/asio.
Boost 1_58_0
g++-4.9.

Thanks for fixing it.

On Sat, Jun 20, 2015 at 5:23 PM, Ken Barker <notifications@github.com>
wrote:

> Thanks you for bringing it to my attention, I've put the fix in the
> develop branch for now.
> BTW which compiler did you use and which version of boost?
> GCC didn't even emit a warning on 1.57, let alone an error...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kenba/via-httplib/issues/3#issuecomment-113718724>.
>



-- 
Joseph Chakravarti Mariadassou
http://thesundayprogrammer.com

**Comment by theSundayProgrammer** [comment]
The modification has not been ported to asio_only branch which is where it won't compile

**Comment by kenba** [comment]
I've now ported the mod to the asio_only branch.

However, please be aware that I'm not planning to maintain the asio_only branch since the asio library itself still depends upon boost...

**Comment by theSundayProgrammer** [comment]
Thanks. 
"asio library itself still depends upon boost"
I got the impression that Chris Kohlhoff was moving towards C++ standards.
