### ISSUE TITLE
Example Client crashes 

### ISSUE THREAD

**Issue by theSundayProgrammer** [kenba/via-httplib#5]
Platform: windows 10 64-bit 
The example client crashes during shutdown because the mutex associated withh http_client is closed earlier when the service goes out of scope. The http_client, declared global, destructs after io_service is destructed.
I'll submit a pull request. Hopefully I fixed the problem correctly.

**Comment by theSundayProgrammer** [comment]
A much simpler solution would be to just <code>http_client=nullptr;</code> just after <code>io_service::run</code>

**Comment by kenba** [comment]
Thank you Joseph.

I've incorporated a slightly different version of your simple solution, i.e. adding `http_client.reset();` just after `io_service::run` since http_client is a `std::shared_ptr`.

**Comment by theSundayProgrammer** [comment]
Thanks. Either solution is fine by me.


On Sat, Jul 9, 2016 at 4:09 AM, Ken Barker <notifications@github.com> wrote:

> Thank you Joseph.
>
> I've incorporated a slightly different version of your simple solution,
> i.e. adding http_client.reset(); just after io_service::run since
> http_client is a std::shared_ptr.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kenba/via-httplib/issues/5#issuecomment-231431627>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATYM43k3VQ0m6TtwBLOEV9lkSyKErYyks5qTpJCgaJpZM4JHmtq>
> .
>



-- 
Joseph Chakravarti Mariadassou
http://thesundayprogrammer.com

**Comment by kenba** [comment]
Closed as resolved.
