### ISSUE TITLE
1.2.0: There's no way to detect that port we are trying to connect does not accepts connections

### ISSUE THREAD

**Issue by antonovvk** [kenba/via-httplib#7]
Hi!
Here's one serious issue.
If we try to connect to some unopened port on localhost, we end up here:
connection.hpp:181 
with errno 111 (connection refused), and go here:
http_client.hpp:188
But the connection_ is not connected() yet, and period_ == 0, so we just do nothing.
And this is a problem, since error just gets ignored and thus client can not handle it.

**Comment by kenba** [comment]
Hi Vladamir, thank you for highlighting this issue.

I have changed the  `disconnected_handler()` at `http_client.hpp`:188 `from:

    if (connection_->connected())
    {
      connection_->set_connected(false);

      if (disconnected_handler_)
        disconnected_handler_();

      connection_->close();
    }

to:

    if (connection_->connected())
    {
      connection_->set_connected(false);
      connection_->close();
    }

    if (disconnected_handler_)
      disconnected_handler_();

This should enable the disconnected_handler_ to be called when `connection_refused` is received.
The code is checked into the develop branch. Please let me know if this change works for you.

**Comment by antonovvk** [comment]
Hi Ken!
Yes, this looks like a quick working solution. 
But I have one more question: what is the difference between disconnected_handler and error_handler (which user can not set)?
On some of my apps I'm getting lots of entries in error_handler with errno 99 and I can't handle that too.
Why don't we have a general error_handler with error code and disconnected flag as parameters?

I'd use that if the server I'm trying to communicate begin rejecting connections for some reason, and I need to wait until it starts recieving them again.

**Comment by antonovvk** [comment]
What do you think about this?
https://github.com/antonovvk/via-httplib/commit/6ca3337622efb60a6a20b7be5b3e8f6a99ea1720

**Comment by kenba** [comment]
Hi Vladamir,
I'm glad to hear that you like the quick solution.
If the change that I made works, then I recommend that you close this issue and open a new issue (with a pull request containing your proposed changes) to enable a user to set an error handler.

You have a good point about the disconnected_handler and error_handler. The code was originally designed for a simple embedded HTTP server; it's scope has expanded over time...
The disconnected_handler was originally designed to detect when a server should disconnect a connection.

Your proposed change looks good, but I think that your change to `connection.hpp` may cause `connection_refused` to be missed again. Both `http_client.cpp` and `http_server.cpp` have an `error_handler` function which could be replaced by an error_handler callback. Those are my initial thoughts on your proposal, but this is a much bigger change and requires careful design not to break the server code.

**Comment by antonovvk** [comment]
Ken thank you very much for your reply!
Yes, let's close this issue with your solution.
I'll open a new issue for the user-defined error handlers and let's discuss it there.
